// Code generated by MockGen. DO NOT EDIT.
// Source: dish.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "quickeat/pkg/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDishService is a mock of DishService interface.
type MockDishService struct {
	ctrl     *gomock.Controller
	recorder *MockDishServiceMockRecorder
}

// MockDishServiceMockRecorder is the mock recorder for MockDishService.
type MockDishServiceMockRecorder struct {
	mock *MockDishService
}

// NewMockDishService creates a new mock instance.
func NewMockDishService(ctrl *gomock.Controller) *MockDishService {
	mock := &MockDishService{ctrl: ctrl}
	mock.recorder = &MockDishServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDishService) EXPECT() *MockDishServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDishService) Get(ctx context.Context, id int) (*entity.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDishServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDishService)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockDishService) GetAll(ctx context.Context) ([]*entity.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entity.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDishServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDishService)(nil).GetAll), ctx)
}

// GetByCategory mocks base method.
func (m *MockDishService) GetByCategory(ctx context.Context, categoryID int) ([]*entity.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", ctx, categoryID)
	ret0, _ := ret[0].([]*entity.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory.
func (mr *MockDishServiceMockRecorder) GetByCategory(ctx, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockDishService)(nil).GetByCategory), ctx, categoryID)
}
