// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Category struct {
	ID     int     `json:"id"`
	Name   string  `json:"name"`
	Dishes []*Dish `json:"dishes"`
}

type Dish struct {
	ID       int       `json:"id"`
	Category *Category `json:"category"`
	Name     string    `json:"name"`
	Price    float64   `json:"price"`
	CookTime int       `json:"cookTime"`
}

type CreateDishInput struct {
	Name     string  `json:"name"`
	Category *int    `json:"category"`
	Price    float64 `json:"price"`
	CookTime int     `json:"cookTime"`
}
